### ISSUE TITLE
Trouble with certain mod

### ISSUE THREAD

**Issue by Jimver** [NathanVaughn/msfs-mod-manager#44]
Hello, upon installing the following livery from flightsim.to: https://flightsim.to/file/3209/united-nations-cessna-208-b
I get an error upon installation (see image below, could not copy the text unfortunately).

It's quite strange as the `layout.json` seems fine to me.

## Expected Behavior
Mod installs successfully without errors

## Actual Behavior
Error given on install:
![afbeelding](https://user-images.githubusercontent.com/7677699/99073129-a0157080-25b5-11eb-8b74-1adef9deb1c8.png)

## Steps to Reproduce the Problem

  1. Download mod at: https://flightsim.to/file/3209/united-nations-cessna-208-b
  2. Install it via the tool
  3. Get error

## Specifications

  - Application Version: `v0.5.1`
  - MSFS Edition: MS Store

## Debug Log Contents (only if reporting a bug)

This file is found at `%APPDATA%\MSFS Mod Manager\debug.log`

(Everything after the last `__main__:<module>:27 - -----------------------` line)

```
2020-11-13 15:16:39.571 | DEBUG    | lib.flight_sim:__init__:50 - Initialzing mod archive installer thread
2020-11-13 15:16:39.574 | DEBUG    | lib.thread:run:21 - Running thread
2020-11-13 15:16:39.589 | DEBUG    | lib.flight_sim:install_mod_archive:497 - Installing mod C:/Users/Jim/Downloads/Asobo_208B_GRAND_CARAVAN_EX_UN_YtQmL.zip
2020-11-13 15:16:39.590 | DEBUG    | lib.flight_sim:extract_mod_archive:432 - Extracting archive C:/Users/Jim/Downloads/Asobo_208B_GRAND_CARAVAN_EX_UN_YtQmL.zip
2020-11-13 15:16:39.595 | DEBUG    | lib.files:delete_folder:143 - Attempting to delete folder C:\Users\Jim\AppData\Local\Temp\MSFS Mod Manager
2020-11-13 15:16:39.605 | DEBUG    | lib.files:create_tmp_folder:241 - Creating temp folder C:\Users\Jim\AppData\Local\Temp\MSFS Mod Manager
2020-11-13 15:16:39.606 | DEBUG    | lib.files:extract_archive:284 - Extracting archive C:/Users/Jim/Downloads/Asobo_208B_GRAND_CARAVAN_EX_UN_YtQmL.zip to C:\Users\Jim\AppData\Local\Temp\MSFS Mod Manager\Asobo_208B_GRAND_CARAVAN_EX_UN_YtQmL
2020-11-13 15:16:39.842 | DEBUG    | lib.flight_sim:install_mods:472 - Installing mod C:\Users\Jim\AppData\Local\Temp\MSFS Mod Manager\Asobo_208B_GRAND_CARAVAN_EX_UN_YtQmL
2020-11-13 15:16:39.843 | DEBUG    | lib.flight_sim:determine_mod_folders:446 - Locating mod folders inside C:\Users\Jim\AppData\Local\Temp\MSFS Mod Manager\Asobo_208B_GRAND_CARAVAN_EX_UN_YtQmL
2020-11-13 15:16:39.845 | DEBUG    | lib.flight_sim:determine_mod_folders:461 - Mod found C:\Users\Jim\AppData\Local\Temp\MSFS Mod Manager\Asobo_208B_GRAND_CARAVAN_EX_UN_YtQmL\Asobo_208B_GRAND_CARAVAN_EX_UN
2020-11-13 15:16:39.853 | DEBUG    | lib.files:move_folder:198 - Moving folder C:\Users\Jim\AppData\Local\Temp\MSFS Mod Manager\Asobo_208B_GRAND_CARAVAN_EX_UN_YtQmL\Asobo_208B_GRAND_CARAVAN_EX_UN to C:\Users\Jim\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community\Asobo_208B_GRAND_CARAVAN_EX_UN
2020-11-13 15:16:39.853 | DEBUG    | lib.files:copy_folder:166 - Copying folder C:\Users\Jim\AppData\Local\Temp\MSFS Mod Manager\Asobo_208B_GRAND_CARAVAN_EX_UN_YtQmL\Asobo_208B_GRAND_CARAVAN_EX_UN to C:\Users\Jim\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community\Asobo_208B_GRAND_CARAVAN_EX_UN
2020-11-13 15:16:39.856 | DEBUG    | lib.files:delete_folder:143 - Attempting to delete folder C:\Users\Jim\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community\Asobo_208B_GRAND_CARAVAN_EX_UN
2020-11-13 15:16:39.880 | DEBUG    | lib.files:get_folder_size:100 - Returning size of C:\Users\Jim\AppData\Local\Temp\MSFS Mod Manager\Asobo_208B_GRAND_CARAVAN_EX_UN_YtQmL\Asobo_208B_GRAND_CARAVAN_EX_UN recursively
2020-11-13 15:16:40.104 | DEBUG    | lib.thread:run:27 - Thread completed
2020-11-13 15:16:40.105 | ERROR    | widgets.main_widget:base_fail:200 - Failed to install mod archive
2020-11-13 15:16:40.105 | ERROR    | widgets.main_widget:base_fail:201 - <class 'shutil.Error'>: [('C:\\Users\\Jim\\AppData\\Local\\Temp\\MSFS Mod Manager\\Asobo_208B_GRAND_CARAVAN_EX_UN_YtQmL\\Asobo_208B_GRAND_CARAVAN_EX_UN\\SimObjects\\Airplanes\\Asobo_208B_GRAND_CARAVAN_EX-UN\\TEXTURE.UN\\CESSNA_208B_GRANDCARAVANEX_AIRFRAME_DECAL_ALBD.PNG.DDS.FLAGS', 'C:\\Users\\Jim\\AppData\\Local\\Packages\\Microsoft.FlightSimulator_8wekyb3d8bbwe\\LocalCache\\Packages\\Community\\Asobo_208B_GRAND_CARAVAN_EX_UN\\SimObjects\\Airplanes\\Asobo_208B_GRAND_CARAVAN_EX-UN\\TEXTURE.UN\\CESSNA_208B_GRANDCARAVANEX_AIRFRAME_DECAL_ALBD.PNG.DDS.FLAGS', "[Errno 2] No such file or directory: 'C:\\\\Users\\\\Jim\\\\AppData\\\\Local\\\\Packages\\\\Microsoft.FlightSimulator_8wekyb3d8bbwe\\\\LocalCache\\\\Packages\\\\Community\\\\Asobo_208B_GRAND_CARAVAN_EX_UN\\\\SimObjects\\\\Airplanes\\\\Asobo_208B_GRAND_CARAVAN_EX-UN\\\\TEXTURE.UN\\\\CESSNA_208B_GRANDCARAVANEX_AIRFRAME_DECAL_ALBD.PNG.DDS.FLAGS'"), ('C:\\Users\\Jim\\AppData\\Local\\Temp\\MSFS Mod Manager\\Asobo_208B_GRAND_CARAVAN_EX_UN_YtQmL\\Asobo_208B_GRAND_CARAVAN_EX_UN\\SimObjects\\Airplanes\\Asobo_208B_GRAND_CARAVAN_EX-UN\\TEXTURE.UN\\CESSNA_208B_GRANDCARAVANEX_AIRFRAME_LIVERY_ALBD.PNG.DDS.json', 'C:\\Users\\Jim\\AppData\\Local\\Packages\\Microsoft.FlightSimulator_8wekyb3d8bbwe\\LocalCache\\Packages\\Community\\Asobo_208B_GRAND_CARAVAN_EX_UN\\SimObjects\\Airplanes\\Asobo_208B_GRAND_CARAVAN_EX-UN\\TEXTURE.UN\\CESSNA_208B_GRANDCARAVANEX_AIRFRAME_LIVERY_ALBD.PNG.DDS.json', "[Errno 2] No such file or directory: 'C:\\\\Users\\\\Jim\\\\AppData\\\\Local\\\\Packages\\\\Microsoft.FlightSimulator_8wekyb3d8bbwe\\\\LocalCache\\\\Packages\\\\Community\\\\Asobo_208B_GRAND_CARAVAN_EX_UN\\\\SimObjects\\\\Airplanes\\\\Asobo_208B_GRAND_CARAVAN_EX-UN\\\\TEXTURE.UN\\\\CESSNA_208B_GRANDCARAVANEX_AIRFRAME_LIVERY_ALBD.PNG.DDS.json'")]
2020-11-13 15:16:41.400 | DEBUG    | lib.flight_sim:get_enabled_mods:383 - Retrieving list of enabled mods
```

**Comment by NathanVaughn** [comment]
I've actually seen this error myself. This is caused by a race condition in the [`files.delete_folder`](https://github.com/NathanVaughn/msfs-mod-manager/blob/3a349d302b3ae6789ae67a1114247daa3b11a15d/src/main/python/lib/files.py#L139) function. This could be one of two causes:
1. A bug with the CPython interpreter with `shutil.rmtree` as outlined in this issue: [https://bugs.python.org/issue29699](https://bugs.python.org/issue29699)
2. My own fault, where `if os.path.isdir(folder)` checks if the folder exists before deleting it, but it no longer exists by the time `shutil.rmtree` tries to delete it, as described more here: [https://github.com/mopidy/mopidy/issues/1766](https://github.com/mopidy/mopidy/issues/1766)

Now, the easy solution is to just set [`ignore_errors=True`](https://docs.python.org/3/library/shutil.html#shutil.rmtree), but I still want some errors being raised so I can attempt to fix directory permissions: [https://blog.nathanv.me/posts/python-permission-issue/](https://blog.nathanv.me/posts/python-permission-issue/)

Anyways, I *think* I've developed a fix, but I have not gotten a chance yet to fully test it and push it to a release.

**Comment by NathanVaughn** [comment]
I was unable to get the issue to occur on my machine to test my fix, but I think it should work.
I've pushed [version 0.5.2](https://github.com/NathanVaughn/msfs-mod-manager/releases/tag/v0.5.2) which incorporates this. I'm going to close the issue for now, but if it comes up still, please just re-open it.

**Comment by Jimver** [comment]
I still get the issue unfortunately this is in v0.5.3:

![afbeelding](https://user-images.githubusercontent.com/7677699/99187085-ca516480-2754-11eb-9134-97d55a5a166b.png)

**Comment by NathanVaughn** [comment]
Just wanted to say, haven't forgotten about this issue. I just graduated from college and am finishing up moving. Hopefully I'll be able to address this next week.

**Comment by NathanVaughn** [comment]
Note for myself:
This issue only occurs when compiled with PyInstaller, not when running on the interpreter directly.

**Comment by NathanVaughn** [comment]
I know I've said this before, but I think I *finally* figured it out and fixed it. I'm fairly certain now that it wasn't some sort of race condition, but in fact that the Windows path to the file was too long (old-school DOS legacy stuff imposes a limit of something like 260 characters), causing the cryptic `FileNotFoundError` even though the file existed. I think I've fixed it by prepending `\\?\` to all file copy/move/delete operations. See this for more info: [https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#win32-file-namespaces](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#win32-file-namespaces)

**Comment by NathanVaughn** [comment]
Should be fixed for real in f904414 and Version 0.5.5. Feel free to re-open if it recoccurs.
